- type: job
  id: JobUSSPSteersman
  name: Штурман
  description: Возьмите управление штурвалом в свои руки!
  playTimeTracker: JobUSSPSteersman # Заглушка
  setPreference: false
  icon: "JobIconUSSPSteersman"
  supervisors: job-supervisors-ussp-centcom
  access:
  - Maintenance
  - External
  canBeAntag: false

- type: job
  id: JobUSSPCommander
  name: Командир
  description: Командуйте и организовывайте экипаж!
  playTimeTracker: JobUSSPCommander # Заглушка
  setPreference: false
  icon: "JobIconADTUSSPArmyOfficer"
  supervisors: job-supervisors-ussp-centcom
  access:
  - Maintenance
  - External
  canBeAntag: false

- type: job
  id: JobUSSPAcoustic
  name: Акустик
  description: Используя бортовое оборудование, вслушивайтесь в пустоты...
  playTimeTracker: JobUSSPAcoustic # Заглушка
  setPreference: false
  icon: "JobIconUSSPAcoustic"
  supervisors: job-supervisors-ussp-centcom
  access:
  - Maintenance
  - External
  canBeAntag: false

- type: job
  id: JobUSSPElectrician
  name: Электромеханик
  description: Контролируйте энергообеспечение объекта!
  playTimeTracker: JobUSSPElectrician # Заглушка
  setPreference: false
  icon: "JobIconUSSPElectrician"
  supervisors: job-supervisors-ussp-centcom
  access:
  - Maintenance
  - External
  canBeAntag: false

- type: job
  id: JobUSSPCook
  name: Кок
  description: Не дайте экипажу умереть от голода!
  playTimeTracker: JobUSSPCook # Заглушка
  setPreference: false
  icon: "JobIconUSSPCook"
  supervisors: job-supervisors-ussp-centcom
  access:
  - Maintenance
  - External
  canBeAntag: false

- type: job
  id: JobUSSPMechanic
  name: Моторист
  description: Контролируйте работу двигателя!
  playTimeTracker: JobUSSPMechanic # Заглушка
  setPreference: false
  icon: "JobIconUSSPMechanic"
  supervisors: job-supervisors-ussp-centcom
  access:
  - Maintenance
  - External
  canBeAntag: false
